workflows:
  wbz_ios_export_testflight:
    name: WBZ iOS Export → TestFlight
    max_build_duration: 120
    environment:
      groups:
        - app_store_connect   # Tạo group này trong Codemagic và thêm 3 biến: APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_ID, APP_STORE_CONNECT_PRIVATE_KEY (nội dung file .p8)
      vars:
        XCODE_SCHEME: "Unity-iPhone"
        XCODE_WORKSPACE: "Unity-iPhone.xcworkspace"   # Nếu chưa run pod install thì workspace chưa có; sau bước pod install sẽ có
        APP_BUNDLE_ID: "com.galacticozstudio.weaponballz"  # <— sửa đúng Bundle ID
        CF_BUNDLE_SHORT_VERSION: "1.0"                # optional: version display (1.0, 1.1…)
    cache:
      cache_paths:
        - ~/.cocoapods
        - ios/Pods
        - Pods
        - ~/Library/Developer/Xcode/DerivedData
    scripts:
      - name: Kiểm tra cấu trúc iOS export
        script: |
          set -e
          ls -la
          test -d "Classes" || { echo "❌ Không thấy folder Classes (repo không phải iOS export?)"; exit 1; }
          test -f "Info.plist" || echo "⚠️ Không thấy Info.plist ở root — kiểm tra lại path nếu cần."

      - name: Cập nhật build number theo CI (tăng tự động)
        script: |
          set -e
          # Codemagic có biến $BUILD_NUMBER tự tăng
          # Ghi build number vào Info.plist (CFBundleVersion); version name giữ ở CF_BUNDLE_SHORT_VERSION
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${CF_BUNDLE_SHORT_VERSION}" Info.plist || /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string ${CF_BUNDLE_SHORT_VERSION}" Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${BUILD_NUMBER}" Info.plist || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string ${BUILD_NUMBER}" Info.plist
          echo "✅ Set CFBundleShortVersionString=${CF_BUNDLE_SHORT_VERSION}, CFBundleVersion=${BUILD_NUMBER}"

- name: Fix CocoaPods repos (remove master, use CDN)
  script: |
    set -e
    set -o pipefail

    echo "→ Repo list trước khi sửa:"
    pod repo list || true

    # Gỡ repo 'master' cũ (đã deprecated)
    if pod repo list | grep -q "/repos/master"; then
      echo "→ Removing deprecated 'master' specs repo…"
      pod repo remove master || true
    fi

    # Đảm bảo dùng CDN 'trunk'
    pod repo add trunk https://cdn.cocoapods.org/ || true
    pod repo update trunk

    echo "→ Repo list sau khi sửa:"
    pod repo list

      - name: Cài CocoaPods
        script: |
          set -e
          pod --version
          # Nếu repo có Podfile ở root export, cài vào ngay tại đây
          if [ -f "Podfile" ]; then
            pod install --deployment || pod install --repo-update
          else
            echo "ℹ️ Không có Podfile — nếu dùng Firebase/Google, nên giữ Podfile để build ổn định."
          fi

      - name: Generate ExportOptions.plist (App Store)
        script: |
          set -e
          cat > ExportOptions.plist << 'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key><string>app-store</string>
              <key>signingStyle</key><string>automatic</string>
              <key>uploadBitcode</key><false/>
              <key>compileBitcode</key><false/>
              <key>destination</key><string>export</string>
            </dict>
          </plist>
          PLIST

      - name: Xcode Archive (Release)
        script: |
          set -e
          set -o pipefail
          # Dùng workspace nếu tồn tại, otherwise dùng project
          if [ -f "${XCODE_WORKSPACE}" ]; then
            echo "➡️ Build bằng workspace: ${XCODE_WORKSPACE}"
            xcodebuild \
              -workspace "${XCODE_WORKSPACE}" \
              -scheme "${XCODE_SCHEME}" \
              -configuration Release \
              -destination generic/platform=iOS \
              DEVELOPMENT_TEAM="${APP_STORE_TEAM_ID}" \
              PRODUCT_BUNDLE_IDENTIFIER="${APP_BUNDLE_ID}" \
              -archivePath "$CM_BUILD_DIR/build.xcarchive" \
              clean archive | xcpretty
          else
            echo "➡️ Không có workspace, build bằng project .xcodeproj"
            xcodebuild \
              -project "Unity-iPhone.xcodeproj" \
              -scheme "${XCODE_SCHEME}" \
              -configuration Release \
              -destination generic/platform=iOS \
              DEVELOPMENT_TEAM="${APP_STORE_TEAM_ID}" \
              PRODUCT_BUNDLE_IDENTIFIER="${APP_BUNDLE_ID}" \
              -archivePath "$CM_BUILD_DIR/build.xcarchive" \
              clean archive | xcpretty
          fi

      - name: Export IPA
        script: |
          set -e
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build.xcarchive" \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath "$CM_BUILD_DIR/ipa"
          ls -la "$CM_BUILD_DIR/ipa"

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
      - $CM_BUILD_DIR/build.xcarchive
      - ExportOptions.plist
      - $HOME/Library/Logs/scan/*.log
      - $CM_BUILD_DIR/**/*.dSYM

    publishing:
      app_store_connect:
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id: $APP_STORE_CONNECT_KEY_ID
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
        # Chọn nhóm nội bộ nếu muốn:
        # beta_groups:
        #   - Internal Testers
        # Release notes cho tester:
        # options:
        #   changelog: "Build $BUILD_NUMBER - Unity iOS export via Codemagic"
